import { useEffect, useRef, useState } from 'react';
import { needsCoApplicant } from '../data/loanOptions';
import Input from '../components/Input';
import Select from '../components/Select';
import StepFormLayout from './StepFormLayout';

const requiredFor = (loanType, panVerified) => {
  const base = [{key:'aadhaarCard',label:'Aadhaar Card (Front & Back)',category:'Identity Documents',required:true},{key:'addressProof',label:'Address Proof',category:'Identity Documents',required:true},{key:'incomeProof',label:'Income Proof',category:'Income Proof',required:true}];
  if (!panVerified) base.push({key:'panCopy',label:'PAN Card Copy',category:'Identity Documents',required:true});
  if (loanType==='home') base.push({key:'propertyDocs',label:'Property Documents',category:'Other',required:true});
  if (loanType==='business') base.push({key:'businessRegistration',label:'Business Registration',category:'Other',required:true},{key:'itr',label:'ITR Documents',category:'Income Proof',required:true});
  return base;
};
const demoFile = (label) => ({name:`demo-${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.pdf`,size:139*1024,type:'application/pdf',demo:true});

export default function Step7Documents({stepNumber,step,formData,onNext,onBack,onSaveDraft,canGoBack,isLastStep}){
 const [files,setFiles]=useState(formData.documents||{}); const [signature,setSignature]=useState(formData.signature||''); const [tab,setTab]=useState('Identity Documents'); const canvasRef=useRef(null); const drawing=useRef(false); const req=requiredFor(formData.loanType,formData.panVerified); const coapp=needsCoApplicant(formData);
 const categories=[...new Set(req.map(r=>r.category)), ...(coapp?['Co-Applicant']:[])];
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';const pt=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*c.width,y:(e.clientY-r.top)/r.height*c.height}};const down=e=>{drawing.current=true;ctx.beginPath();const p=pt(e);ctx.moveTo(p.x,p.y);c.setPointerCapture?.(e.pointerId)};const move=e=>{if(!drawing.current)return;const p=pt(e);ctx.lineTo(p.x,p.y);ctx.stroke()};const up=()=>{if(drawing.current){drawing.current=false;setSignature(c.toDataURL('image/png'))}};c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);c.addEventListener('pointerup',up);c.addEventListener('pointercancel',up);return()=>{c.removeEventListener('pointerdown',down);c.removeEventListener('pointermove',move);c.removeEventListener('pointerup',up);c.removeEventListener('pointercancel',up)}},[]);
 const addFiles=(key,list)=>{const valid=[...list].filter(f=>['application/pdf','image/jpeg','image/png'].includes(f.type)&&f.size<=5*1024*1024).slice(0,3).map(f=>({name:f.name,size:f.size,type:f.type}));setFiles(p=>({...p,[key]:valid}))};
 const attachDemo=()=>{const next={};req.forEach(r=>next[r.key]=[demoFile(r.label)]);setFiles(next);setTimeout(()=>addDemoSignature(),0)};
 const addDemoSignature=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#173b91';ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(80,110);ctx.bezierCurveTo(140,30,170,150,240,85);ctx.bezierCurveTo(300,25,340,145,410,75);ctx.bezierCurveTo(470,35,540,120,610,65);ctx.stroke();setSignature(c.toDataURL('image/png'))};
 const clearSig=()=>{canvasRef.current?.getContext('2d').clearRect(0,0,700,180);setSignature('')};
 const visible=req.filter(r=>r.category===tab); const uploaded=req.filter(r=>files[r.key]?.length).length; const complete=uploaded===req.length && !!signature;
 const submit=e=>{e.preventDefault();if(!complete)return;onNext({documents:files,signature,coApplicantName:formData.coApplicantName,coApplicantRelationship:formData.relationship,coApplicantIncome:formData.coApplicantIncome})};
 return <StepFormLayout stepNumber={stepNumber} title="Document Upload" description="Upload the documents required for your loan type and capture your electronic signature." errors={!complete?{documents:{message:'Complete required documents and signature before continuing'}}:{}} onBack={onBack} onSaveDraft={()=>onSaveDraft({documents:files,signature})} canGoBack={canGoBack} isLastStep={isLastStep} isSubmitting={false} getValues={()=>({documents:files,signature})} onSubmit={submit}>
   <div className="space-y-5">
    <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center gap-4 text-sm"><span><b>Loan Type:</b> <span className="rounded-full bg-blue-50 px-2 py-1 text-blue-700">{formData.loanType||'Personal'}</span></span><span><b>Employment:</b> <span className="rounded-full bg-blue-50 px-2 py-1 text-blue-700">{formData.employmentType||'Salaried'}</span></span><span><b>PAN Verified:</b> <span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">{formData.panVerified?'Yes (PAN upload optional)':'No'}</span></span></div></div>
    <div className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-4 text-sm"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-amber-400"/>Pending: {Math.max(0,req.length-uploaded)}</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-500"/>Uploaded: {uploaded}</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-500"/>Verified: {formData.panVerified?1:0}</span></div><div className="flex items-center gap-3"><button type="button" onClick={attachDemo} className="rounded-lg border-2 border-emerald-300 bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">⚡ Attach Fictional Demo Files</button><span className="text-sm font-bold text-amber-600">{uploaded} of {req.length} required complete</span></div></div></div>
    <div className="flex overflow-x-auto border-b border-slate-200">{categories.filter(c=>c!=='Co-Applicant').map(c=><button key={c} type="button" onClick={()=>setTab(c)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${tab===c?'border-emerald-600 text-emerald-700':'border-transparent text-slate-500'}`}>{c} {req.some(r=>r.category===c&&r.required)?'*':''}</button>)}</div>
    {coapp&&<fieldset className="rounded-xl border border-slate-200 p-5"><legend className="px-2 text-base font-bold">Co-Applicant Details</legend><div className="grid gap-5 md:grid-cols-2"><Input id="coApplicantName" required><Input.Label>Co-Applicant Name</Input.Label><Input.Field defaultValue={formData.coApplicantName||''} onChange={()=>{}} /></Input><Select id="relationship"><Select.Label>Relationship</Select.Label><Select.Field defaultValue={formData.maritalStatus==='Married'?'Spouse':''}><option value="">Select relationship</option><option>Spouse</option><option>Parent</option><option>Sibling</option><option>Business Partner</option></Select.Field></Select></div></fieldset>}
    <div className="space-y-4">{visible.map(r=><div key={r.key} className="rounded-xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{r.label} {r.required&&<span className="text-red-600">*</span>}</h3><p className="text-xs text-slate-500">PDF, JPEG, PNG • Max 2 files • 5 MB each</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${files[r.key]?.length?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{files[r.key]?.length?'Uploaded':'Pending'}</span></div><label className="mt-4 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-white text-center"><span className="text-3xl text-slate-400">☁</span><span className="mt-2 font-semibold">Click or drag files to upload</span><span className="text-xs text-slate-500">PDF, JPEG, PNG • Max 2 file(s) • 5 MB each</span><input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" multiple onChange={e=>addFiles(r.key,e.target.files)}/></label>{files[r.key]?.map(f=><div key={f.name} className="mt-2 flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm"><span>📄 {f.name}</span><span>{Math.max(1,Math.round(f.size/1024))} KB</span></div>)}</div>)}</div>
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">E-Signature <span className="text-red-600">*</span></h3><p className="text-sm text-slate-500">Digital signature captured via canvas.</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${signature?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{signature?'Uploaded':'Pending'}</span></div><canvas ref={canvasRef} width="700" height="180" aria-label="Electronic signature drawing area" className="mt-4 h-44 w-full touch-none rounded-lg border border-slate-200 bg-white"/><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={addDemoSignature} className="rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700">⚡ Add Demo Signature</button><button type="button" onClick={clearSig} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">✕ Clear</button><button type="button" disabled={!signature} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-40">⇩ Download</button></div>{signature&&<p className="mt-2 text-sm font-semibold text-emerald-700">✓ Signature captured</p>}</section>
   </div>
 </StepFormLayout>
}
