import { useState } from 'react';
import StepFormLayout from './StepFormLayout';
import { getLoanConfig } from '../data/loanOptions';
import { calculateEMI, processingFee, formatINRValue } from '../utils/emiCalculator';

export default function Step8Review({ stepNumber, step, formData, onNext, onBack, onSaveDraft, canGoBack, isLastStep }) {
 const [consents,setConsents]=useState([true,true,true,true]); const [submitted,setSubmitted]=useState(false); const cfg=getLoanConfig(formData.loanType); const emi=calculateEMI(formData.loanAmount,cfg.annualRate,formData.loanTenure); const income=Number(formData.monthlyNetSalary||formData.monthlyIncome||0)+Number(formData.coApplicantIncome||0); const ratio=income?emi/income:0;
 const toggle=i=>setConsents(c=>c.map((v,j)=>j===i?!v:v)); const submit=()=>{if(!consents.every(Boolean))return;const reference=crypto.randomUUID?crypto.randomUUID():`LS-${Date.now()}`;setSubmitted(true);onNext({submitted:true,applicationReference:reference})};
 if(submitted)return <div className="space-y-6"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-7 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-2xl text-white">✓</div><h2 className="mt-4 text-2xl font-bold">Application Submitted</h2><p className="mt-2 text-slate-600">Your fictional assessment application has been submitted successfully.</p><p className="mt-4 font-mono text-sm">Reference: {formData.applicationReference||'Generated'}</p></div></div>;
 const edit=()=>{};
 return <StepFormLayout stepNumber={stepNumber} title="Review & Confirm" description="Review all information before submitting your loan application." errors={{}} onBack={onBack} onSaveDraft={onSaveDraft} canGoBack={canGoBack} isLastStep={true} isSubmitting={false} getValues={()=>({})} onSubmit={e=>{e.preventDefault();submit()}}>
   <div className="space-y-5">
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Loan Details</h3><button type="button" onClick={edit} className="font-semibold text-emerald-700">Edit</button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Loan Type</dt><dd className="font-semibold">{cfg.label}</dd></div><div><dt className="text-xs text-slate-500">Loan Amount</dt><dd className="font-semibold">{formatINRValue(formData.loanAmount)}</dd></div><div><dt className="text-xs text-slate-500">Tenure</dt><dd className="font-semibold">{formData.loanTenure||'—'} months</dd></div><div><dt className="text-xs text-slate-500">Purpose</dt><dd className="font-semibold">{formData.loanPurpose||'—'}</dd></div></dl></section>
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Personal Information</h3><button type="button" onClick={edit} className="font-semibold text-emerald-700">Edit</button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 text-sm"><div><dt className="text-slate-500">Name</dt><dd>{formData.fullName||'—'}</dd></div><div><dt className="text-slate-500">Date of Birth</dt><dd>{formData.dateOfBirth||'—'}</dd></div><div><dt className="text-slate-500">Gender</dt><dd>{formData.gender||'—'}</dd></div><div><dt className="text-slate-500">Marital Status</dt><dd>{formData.maritalStatus||'—'}</dd></div><div><dt className="text-slate-500">Mobile Number</dt><dd>{formData.mobile||'—'}</dd></div><div><dt className="text-slate-500">Email</dt><dd>{formData.email||'—'}</dd></div></dl></section>
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Identity / KYC</h3><button type="button" onClick={edit} className="font-semibold text-emerald-700">Edit</button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 text-sm"><div><dt className="text-slate-500">PAN</dt><dd>{formData.panNumber?`${formData.panNumber.slice(0,5)}****${formData.panNumber.slice(-1)}`:'—'}</dd></div><div><dt className="text-slate-500">PAN Verified</dt><dd>{formData.panVerified?'Yes':'No'}</dd></div><div><dt className="text-slate-500">Aadhaar</dt><dd>{formData.aadhaarNumber?`**** **** ${formData.aadhaarNumber.slice(-4)}`:'—'}</dd></div><div><dt className="text-slate-500">Aadhaar Verified</dt><dd>{formData.aadhaarVerified?'Yes':'No'}</dd></div><div><dt className="text-slate-500">Voter ID</dt><dd>{formData.voterId||'—'}</dd></div></dl></section>
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Address Information</h3><button type="button" onClick={edit} className="font-semibold text-emerald-700">Edit</button></div><p className="mt-3 text-sm">{formData.currentAddress1||'—'}{formData.currentAddress2?`, ${formData.currentAddress2}`:''}</p><p className="text-sm text-slate-600">{formData.currentCity||''}, {formData.currentState||''} - {formData.currentPin||''}</p></section>
    <section className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Employment &amp; Income</h3><button type="button" onClick={edit} className="font-semibold text-emerald-700">Edit</button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 text-sm"><div><dt className="text-slate-500">Employment</dt><dd>{formData.employmentType||'—'}</dd></div><div><dt className="text-slate-500">Company</dt><dd>{formData.companyName||formData.businessName||'—'}</dd></div><div><dt className="text-slate-500">Monthly Income</dt><dd>{formatINRValue(formData.monthlyNetSalary||formData.monthlyIncome||0)}</dd></div><div><dt className="text-slate-500">Experience</dt><dd>{formData.yearsExperience||'—'} years</dd></div></dl></section>
    <section className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="text-lg font-bold">Pre-Approval Summary</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><span className="text-xs text-slate-500">Loan Amount</span><p className="font-bold">{formatINRValue(formData.loanAmount)}</p></div><div><span className="text-xs text-slate-500">Indicative Interest Rate</span><p className="font-bold">{cfg.annualRate}% p.a.</p></div><div><span className="text-xs text-slate-500">Estimated EMI</span><p className="font-bold">{formatINRValue(emi)}</p></div><div><span className="text-xs text-slate-500">Processing Fee</span><p className="font-bold">{formatINRValue(processingFee(formData.loanAmount))}</p></div><div><span className="text-xs text-slate-500">Total Cost of Borrowing</span><p className="font-bold">{formatINRValue(emi*Number(formData.loanTenure||0)-Number(formData.loanAmount||0))}</p></div></div>{ratio>0.5&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Warning: estimated EMI is more than 50% of monthly income.</p>}</section>
    <section className="rounded-xl border border-slate-200 p-5"><p className="mb-4 text-sm text-slate-500">Please read and confirm each consent below. All are required to proceed.</p>{['Data Collection & Processing','Credit Bureau Check','Communication Preferences','Data Sharing with Third Parties'].map((t,i)=><label key={t} className="mb-3 flex gap-3 rounded-lg border border-slate-200 p-4"><input type="checkbox" checked={consents[i]} onChange={()=>toggle(i)} className="mt-1"/><span><strong>{t}</strong><span className="block mt-1 text-sm text-slate-600">I consent to LendSwift processing my application information for the purpose of this assessment simulation.</span></span></label>)}{consents.every(Boolean)&&<p className="text-sm font-semibold text-emerald-700">✓ All required consents confirmed.</p>}</section>
    <button type="submit" disabled={!consents.every(Boolean)} className="min-h-12 w-full rounded-lg bg-emerald-600 px-6 py-3 font-bold text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50">Submit Application</button>
   </div>
 </StepFormLayout>;
}
