import { useForm, useWatch } from 'react-hook-form';
import Input from '../components/Input';
import Select from '../components/Select';
import StepFormLayout from './StepFormLayout';

export default function Step5Employment({ stepNumber, step, formData, onNext, onBack, onSaveDraft, canGoBack, isLastStep }) {
  const { register, handleSubmit, getValues, control, reset, formState:{errors,isSubmitting} } = useForm({ mode:'onBlur', defaultValues:{ employmentType: formData.employmentType || '', ...formData } });
  const type = useWatch({ control, name:'employmentType' });
  const demo = { employmentType:'Salaried', companyName:'TechCorp Solutions Pvt. Ltd.', designation:'Senior Software Engineer', monthlyNetSalary:'85000', yearsExperience:'5' };
  return <StepFormLayout stepNumber={stepNumber} title={step.title} description="Tell us about your employment so we can assess your repayment capacity." errors={errors} onBack={onBack} onSaveDraft={onSaveDraft} canGoBack={canGoBack} isLastStep={isLastStep} isSubmitting={isSubmitting} getValues={getValues} onSubmit={handleSubmit((data)=>{ if(formData.loanType==='business'&&type==='Salaried') return; onNext(data); })}>
    <div className="mb-5 flex justify-end"><button type="button" onClick={()=>reset({...formData,...demo})} className="rounded-lg border border-emerald-300 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700">⚡ Load Demo Employment</button></div>
    <fieldset><legend className="mb-2 text-sm font-semibold">Employment Type <span className="text-red-600">*</span></legend><div className="grid gap-3 md:grid-cols-3">{['Salaried','Self-Employed','Business Owner'].map(v=><label key={v} className={`flex cursor-pointer items-center justify-center rounded-lg border-2 p-3 font-semibold ${type===v?'border-emerald-500 bg-emerald-50 text-emerald-700':'border-slate-200 bg-white'}`}><input type="radio" className="sr-only" value={v} {...register('employmentType',{required:'Select employment type'})}/>{v}</label>)}</div>{errors.employmentType&&<p className="mt-1 text-sm text-red-600">{errors.employmentType.message}</p>}</fieldset>
    {formData.loanType==='business'&&type==='Salaried'&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">Business loans require Business Owner or Self-Employed.</p>}
    {type==='Salaried'&&<fieldset className="rounded-xl border border-slate-200 p-5"><legend className="px-2 text-base font-bold">Salaried Employment Details</legend><div className="grid gap-5 md:grid-cols-2"><Input id="companyName" required error={errors.companyName?.message}><Input.Label>Company Name</Input.Label><Input.Field {...register('companyName',{required:'Company name is required'})}/><Input.Error/></Input><Input id="designation" required error={errors.designation?.message}><Input.Label>Designation</Input.Label><Input.Field {...register('designation',{required:'Designation is required'})}/><Input.Error/></Input><Input id="monthlyNetSalary" required error={errors.monthlyNetSalary?.message} hint="Minimum ₹15,000 per month"><Input.Label>Monthly Net Salary</Input.Label><Input.Field {...register('monthlyNetSalary',{required:'Monthly net salary is required',validate:v=>Number(v)>=15000||'Minimum monthly net salary is ₹15,000'})} inputMode="numeric"/><Input.HelpText/><Input.Error/></Input><Input id="yearsExperience" required error={errors.yearsExperience?.message} hint="Whole years between 0 and 50."><Input.Label>Years of Experience</Input.Label><Input.Field {...register('yearsExperience',{required:'Years of experience is required',min:{value:0,message:'Cannot be negative'},max:{value:50,message:'Maximum is 50 years'}})} type="number" min="0" max="50"/><Input.HelpText/><Input.Error/></Input></div></fieldset>}
    {type && type!=='Salaried'&&<fieldset className="rounded-xl border border-slate-200 p-5"><legend className="px-2 text-base font-bold">{type} Details</legend><div className="grid gap-5 md:grid-cols-2"><Input id="businessName" required error={errors.businessName?.message}><Input.Label>Business Name</Input.Label><Input.Field {...register('businessName',{required:'Business name is required'})}/><Input.Error/></Input><Select id="businessType" required error={errors.businessType?.message}><Select.Label>Business Type</Select.Label><Select.Field {...register('businessType',{required:'Business type is required'})}><option value="">Select type</option><option>Proprietorship</option><option>Partnership</option><option>Private Limited</option><option>LLP</option></Select.Field><Select.Error/></Select><Input id="annualTurnover" required error={errors.annualTurnover?.message}><Input.Label>Annual Turnover</Input.Label><Input.Field {...register('annualTurnover',{required:'Annual turnover is required',validate:v=>Number(v)>=300000||'Minimum annual turnover is ₹3,00,000'})} inputMode="numeric"/><Input.Error/></Input><Input id="yearsInBusiness" required error={errors.yearsInBusiness?.message}><Input.Label>Years in Business</Input.Label><Input.Field {...register('yearsInBusiness',{required:'Years in business is required',validate:v=>Number(v)>=2||'Minimum is 2 years'})} type="number" min="2"/><Input.Error/></Input>{type==='Self-Employed'&&<Input id="monthlyIncome" required error={errors.monthlyIncome?.message}><Input.Label>Monthly Income</Input.Label><Input.Field {...register('monthlyIncome',{required:'Monthly income is required'})} inputMode="numeric"/><Input.Error/></Input>}{type==='Business Owner'&&<><Input id="gstNumber" required error={errors.gstNumber?.message}><Input.Label>GST Number</Input.Label><Input.Field {...register('gstNumber',{required:'GST number is required',pattern:{value:/^\d{2}[A-Z0-9]{13}$/i,message:'GST number must contain 15 characters'}})} maxLength={15}/><Input.Error/></Input><Input id="businessAddress" required error={errors.businessAddress?.message}><Input.Label>Office / Business Address</Input.Label><Input.Field {...register('businessAddress',{required:'Business address is required'})}/><Input.Error/></Input></>}</div></fieldset>}
  </StepFormLayout>;
}
